name: Run npm command on Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  run-npm-command:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your desired Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run your npm command
      - name: Run npm command
        run: npm run build # Replace 'your-command' with the desired npm script
